version: '3'

services:
  app:
    image: rojima1/clojure
    privileged: true
    command: emacs
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./m2:/home/developer/.m2
      - ./lein:/home/developer/.lein
