version: '3'

services:
  app:
    build: .
    privileged: true
    command: emacs
    working_dir: /home/developer/robosight
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/home/developer/robosight
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./m2:/home/developer/.m2
      - ./lein:/home/developer/.lein
