version: '3'

services:
  app:
    build: .
    privileged: true
    command: emacs
    working_dir: /home/developer/robosight
    environment:
      - DISPLAY=${DISPLAY}
      - PATH=/usr/local/nvidia/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LD_LIBRARY_PATH=/usr/local/nvidia/lib64
    volumes:
      - .:/home/developer/robosight
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./m2:/home/developer/.m2
      - ./lein:/home/developer/.lein
      - nvidia_driver_381.22:/usr/local/nvidia

volumes:
  nvidia_driver_381.22:
    external: true
